export class Student {
    nome: string;
    sobre: string;
    telefone: string;
    indicou: string;
    password: string;
    repita: string;
    z: any;
    x: any;
    c: any;
    v: any;
    b: any;
    n: any;
    recursiva: any;
    time: number = 0;
    interval;
    play: any;
    i: any;
    bola: any = [];
    safra: any = [];
    safraa: any = [];
    safraaa: any = [];
    safraaaa: any = [];
    safraaaaa: any = [];
    safraaaaaa: any = [];
    a: any = [];
    cartela: any = [];
    teste: any;
    tantascartela: any;
    serie: any = [];
    lote: any = [];
    bolas: any = [];
    bolass: any = [];
    ponto: any = 0;
    pontoo: any = 0;
    opa: any;
    bolay: any;
    lili: any = [];
    lilica: any = [];
    lilicaca: any;
    aa: any;
    sorteadas: any = 0;
    currentScreenOrientation: string;
    timeLeft: number = 60;
    ii: any = 0;
    pi: any;
    numero: any;
    papa: any;
    valores: any = [];
    ee;
    soma: any;
    min: any = [];
    linhaa: any;
    mina: any = [];
    minaa: any = [];
    audio: any;
    linex: any;
    zz: any;
    zzz: any;
    xx: any;
    xxx: any;
    cc: any;
    ccc: any;
    vv: any;
    vvv: any;
    bb: any;
    bbb: any;
    tu: any = [];
    linhaaaaa: any;
    saldo: any;
    linhafoi: any;
    linhasim: any;
    modalController: any;
    element: any;
    resultadolinha: any;
    tipo: any;
    resultadobingo: any;
    linhabingo: any;
    pes: any;
    sala: any;
    price: any;
    pbingo: any;
    plinha: any;
    quant: any;
    lapa: any;
    seriea: any = [];
    serieb: any = [];
    lila: any;
    numerolinha: any = [];
    valor: any;
    xs: any;
    xss: any;
    xsss: any;
    xssss: any;
    xsssss: any;
    zs: any;
    zss: any;
    zsss: any;
    zssss: any;
    zsssss: any;
    cs: any;
    css: any;
    csss: any;
    cssss: any;
    csssss: any;
    vela: any = [];
}
